; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.21005.1 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	?xrMemCopy_x86@@YAXPEAXPEBXI@Z			; xrMemCopy_x86
PUBLIC	?xrMemCopy_MMX@@YAXPEAXPEBXI@Z			; xrMemCopy_MMX
; Function compile flags: /Ogtpy
; File c:\x-ray\stcop\rgs\src\xrcore\xrmemory_pso_copy.cpp
;	COMDAT ?xrMemCopy_MMX@@YAXPEAXPEBXI@Z
_TEXT	SEGMENT
dest$ = 8
src$ = 16
n$ = 24
?xrMemCopy_MMX@@YAXPEAXPEBXI@Z PROC			; xrMemCopy_MMX, COMDAT

; 13   :     memcpy (dest,src,n);

	mov	r8d, r8d
	jmp	memcpy
?xrMemCopy_MMX@@YAXPEAXPEBXI@Z ENDP			; xrMemCopy_MMX
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\x-ray\stcop\rgs\src\xrcore\xrmemory_pso_copy.cpp
;	COMDAT ?xrMemCopy_x86@@YAXPEAXPEBXI@Z
_TEXT	SEGMENT
dest$ = 8
src$ = 16
n$ = 24
?xrMemCopy_x86@@YAXPEAXPEBXI@Z PROC			; xrMemCopy_x86, COMDAT

; 7    :     memcpy(dest, src, n);

	mov	r8d, r8d
	jmp	memcpy
?xrMemCopy_x86@@YAXPEAXPEBXI@Z ENDP			; xrMemCopy_x86
_TEXT	ENDS
END
