; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.21005.1 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	?xrMemFill_x86@@YAXPEAXHI@Z			; xrMemFill_x86
; Function compile flags: /Ogtpy
; File c:\x-ray\stcop\rgs\src\xrcore\xrmemory_pso_fill.cpp
;	COMDAT ?xrMemFill_x86@@YAXPEAXHI@Z
_TEXT	SEGMENT
dest$ = 8
value$ = 16
count$ = 24
?xrMemFill_x86@@YAXPEAXHI@Z PROC			; xrMemFill_x86, COMDAT

; 6    :     memset(dest, int(value), count);

	mov	r8d, r8d
	jmp	memset
?xrMemFill_x86@@YAXPEAXHI@Z ENDP			; xrMemFill_x86
_TEXT	ENDS
END
